### ISSUE TITLE
CGRCT creation and CSPTK similarity computation

### ISSUE THREAD

**Issue by mgravina1** [SAG-KeLP/kelp-full#10]
Hi,

I've seen that kelp-input-generator provide the possibility to generate GRCT, LOCT, LCT, so I was wondering if there is also way to generate the Compositional Grammatical Relation Centered Tree of a sentence using KeLP. 

I've also read [issue 6](https://github.com/SAG-KeLP/kelp-full/issues/6) and seen how kernel similarity between two tree representation is computed using SubSetTreeKernel, SubTreeKernel and PartialTreeKernel. Is there a way to compute such similarity using a Compositionally Smoothed Partial Tree Kernel?

Thanks in advance

Best regards 
Marco

**Comment by crux82** [comment]
Dear Marco, 

we just planned to extend the kelp-input-generator project in the next (hopefully few) days to generate also the CGRCTree.  
Please stay tuned!

Best regards

Danilo

**Comment by mgravina1** [comment]
Wonderful! 
I'll wait for it! 

Thank you for your answer.

Regards
Marco

**Comment by crux82** [comment]
Dear Marco, 

I have just implemented the generation of the CGRCTree in the last development branch of the kelp-input-generator project. We are still checking that everything is OK, but you can take a look at it (and maybe support our bug checking).

Best regards

Danilo

**Comment by mgravina1** [comment]
Hello Danilo,

thank you for telling me.
I will shortly try to integrate them in my work!

Best regards
Marco
