### ISSUE TITLE
TreeKernel similarity computation

### ISSUE THREAD

**Issue by mgravina1** [SAG-KeLP/kelp-full#11]
Hi,

I'm trying to compute similarity between two _TreeRepresentations_ using different Kernel Type.
I'm following the example reported by @crux82 in [ISSUE 6](https://github.com/SAG-KeLP/kelp-full/issues/6) but I'm encountering some problems.

Whenever I compute similarity between two different _TreeRepresentation_ objects using _SubTreeKernel_ and _SubSetTreeKernel_, I get the same value. 
The two values are different only if I try to compute such similarities over the same object.
For example:

```
TreeRepresentation t1 = new TreeRepresentation();
t1.setDataFromText("(a (b) (c (d)))");
TreeRepresentation t2 = new TreeRepresentation();
t2.setDataFromText("(a (b) (c (d)))");

SubSetTreeKernel subSetTreeKernel = new SubSetTreeKernel(1f, "tree");
SubTreeKernel subTreeKernel = new SubTreeKernel(1f, "tree");

System.out.println("CASE 1:");
System.out.println("Similarity t1-t2 SubSetTreeKernel res = " + subSetTreeKernel.kernelComputation(t1, t2));
System.out.println("Similarity t1-t2 SubTreeKernel res = " + subTreeKernel.kernelComputation(t1, t2));

System.out.println("CASE 2:");
System.out.println("Similarity t1-t1 SubSetTreeKernel res = " + subSetTreeKernel.kernelComputation(t1, t1));
System.out.println("Similarity t1-t1 SubTreeKernel res = " + subTreeKernel.kernelComputation(t1, t1));
```

OUTPUT: 
_CASE 1
Similarity **t1-t2** SubSetTreeKernel res = 4.0
Similarity **t1-t2** SubTreeKernel res = 4.0
CASE 2
Similarity **t1-t1** SubSetTreeKernel res = 5.0
Similarity **t1-t1** SubTreeKernel res = 4.0_

Am I doing it wrong or the similarities should be 5.0 (for SST) and 4.0 (for ST) in both cases?

Would it also be possible to have an example of how similarity is computed using _SmoothedPartialTreeKernel_ with different _StructureElementSimilarity_?

Thank you so much for your kind attention.

Best regards
Marco

**Comment by SimoneFilice** [comment]
Hi Marco,

It seems that there is a bug on the SubSetTreeKernel. 
Since t1=t2, we expect that SSTK(t1,t2) = SSTK(t1,t1) = SSTK(t2,t2) = 5.
I am investigating on this bug, I will fix it asap.

Best,
Simone

**Comment by SimoneFilice** [comment]
Hi Marco,
I should have solved the bug (which was actually affecting both STK and SSTK, although with your toy example it was visible only on the SSTK). After additional sanity check we will release the new version. For the moment, please use the development branch of the last version of KeLP to get the problem solved.

Cheers,
Simone

**Comment by mgravina1** [comment]
Hello @SimoneFilice ,

thank you very much for your reply and solution.

I'm still struggling to understand some results, but I think it's due to something that I still can't get in the definition of the different kernel trees. 

I'm considering the definitions reported in KeLP website ([these](http://www.kelp-ml.org/?page_id=728)) and I'm executing these lines of code:

```
float lambda = 1f; 
float mu = 1f; 
int terminal_factor = 1;
float threshold = 0.001f;
		
TreeRepresentation t1 = new TreeRepresentation();
t1.setDataFromText("(a (b) (c (d)))");
TreeRepresentation t2 = new TreeRepresentation();
t2.setDataFromText("(a (b) (c (d (e))))");
				
SubSetTreeKernel subSetTreeKernel = new SubSetTreeKernel(lambda, "tree");
SubTreeKernel subTreeKernel = new SubTreeKernel(lambda, "tree");
PartialTreeKernel partialTreeKernel = new PartialTreeKernel(lambda, mu, terminal_factor, "tree");
		
System.out.println("Similarity t1-t2 SubTreeKernel res = " + subTreeKernel.kernelComputation(t1, t2));
System.out.println("Similarity t1-t2 SubSetTreeKernel res = " + subSetTreeKernel.kernelComputation(t1, t2));
System.out.println("Similarity t1-t2 PartialTreeKernel res = " + partialTreeKernel.kernelComputation(t1, t2));
```

The output I get is:
_Similarity t1-t2 SubTreeKernel res = 3.0
Similarity t1-t2 SubSetTreeKernel res = 4.0
Similarity t1-t2 PartialTreeKernel res = 10.0_

I can understand why I get 10 as PartialTreeKernel similarity result, but I can't figure out the other results.
I'm reasoning as follows: 
________________________________________________________________________________________________________
**SubTree(s)** I caculate SubTrees as "_nodes with their complete descendancy_":

_subTrees for t1_
(a (b) (c (d))), (c (d)), **(b)**, (d)

_subTrees for t2_
(a (b) (c (d (e)))), (c (d (e))), (d (e)), **(b)**, (e)

so I expect to get "1" as similarity value between t1 and t2

________________________________________________________________________________________________________
**SubSetTree(s)** I caculate SubSetTrees as "_nodes with either all their children or none of them_":

_subSetTrees for t1_
**(a (b) (c (d)))**, **(c (d))**, **(a (b) (c))**, **(a)**, **(b)**, **(c)**, **(d)**

_subSetTrees for t2_

**(a (b) (c (d)))**, **(c (d))**, **(a (b) (c))**, **(a)**, **(b)**, **(c)**, **(d)**, (a (b) (c (d (e)))),  (c (d (e))), (d (e)), (e)

so I expect to get "7" as similarity value between t1 and t2

________________________________________________________________________________________________________
As partialTees (considered as "_nodes with their partial production and descendancy_") I expect to find all subSetTrees plus:

_additional partialTrees for t1_
**(a (b)), (a (c)), (a (c (d))**

_additional partialTrees for t2_
**(a (b)), (a (c)), (a (c (d))**, (a (c (d (e))))

so I expect to get "10" as similarity value between t1 and t2
________________________________________________________________________________________________________

Am I wrong?

Thanks for your attention.

Best regards
Marco

**Comment by SimoneFilice** [comment]
Hi Marco,

I'm sorry for the late answer, but solving the issue required a bit. Again, please use the development branch until we release a new version of KeLP. 
Let's clarify how the Subtree Kernel and SubSet Tree Kernel work in their standard setting. They both search for common productions in trees. This means that individual nodes are not considered valid matching fragments. 
So, given the trees t1=(a (b) (c (d))) and t2=(a (b) (c (d (e)))) , we have the following kernel computations:

### SUB TREE KERNEL

STK(t1,t2) = 0, as no common productions occur.

STK(t1,t1) = 2, and the matching fragments are:
1. (a (b) (c (d))) 
2. (c (d))

### SUBSET TREE KERNEL

SSTK(t1,t2) = 3, and the matching fragments are the followings:
1. (a (b) (c)) 
2. (a (b) (c (d))) 
3. (c (d))

SSTK(t1,t1) = 3, and the matching fragments are:
1. (a (b) (c)) 
2. (a (b) (c (d))) 
3. (c (d))

Please consider that by default the KeLP implementations of the STK and SSTK also perform a matching between tree leaves. In constituency trees where leaves are words, this corresponds to combine the tree kernel with a linear kernel on a Bag-of-Word representation. To disable this additional analysis you need to use the _setIncludeLeaves_ method:
`subTreeKernel.setIncludeLeaves(false);`
`subSetTreeKernel.setIncludeLeaves(false);`

If you don't disable it you will observe the following kernel results:
STK(t1,t2) = 1
STK(t1,t1) = 4
SSTK(t1,t2) = 4
SSTK(t1,t1) = 5

Thanks for your patience. We really appreciated your questions that made us discover this bug we were not aware of.

Best,
Simone

**Comment by mgravina1** [comment]
Hello Simone, 

thank you for the answer and the explanation, now everything is clearer. 

I close the issue since it has been solved.

Thanks again,

regards
Marco
