### ISSUE TITLE
Incremental training 

### ISSUE THREAD

**Issue by karoaper** [SAG-KeLP/kelp-full#12]
Hi,
I have a quick question about your library.
Is it possible to train a model, save it in json, then load it, and continue training?

**Comment by SimoneFilice** [comment]
Hi karoaper,

yes you can do it. After the first training stage you need to save in json both the LearningAlgorithm and the learned PredictionFunction. Then, when you want to restart learning, you need to use the following procedure (assuming that `jsonFileAlgo` and `jsonFilePredFun` are the `File` objects for reading the json files saved before) :
```
ObjectSerializer serializer = new JacksonSerializerWrapper();
LearningAlgorithm learningAlgo = serializer.readValue(jsonFileAlgo, LearningAlgorithm.class);
PredictionFunction learnedPredFun = serializer.readValue(jsonFilePredFun, PredictionFunction.class);
learningAlgo.getPredictionFunction().setModel(learnedPredFun.getModel());
```

A similar example of this procedure is available in this [unit test](https://github.com/SAG-KeLP/kelp-additional-algorithms/blob/development/src/test/java/it/uniroma2/sag/kelp/algorithms/incrementalTrain/IncrementalTrainTest.java)
