### ISSUE TITLE
FixIndexKernelCache

### ISSUE THREAD

**Issue by redhome333** [SAG-KeLP/kelp-full#15]
Hi, 
I have a 70,000 row data set, and I have converted them into LCT. When I run classification, I got NegativeArraySizeException and the message indicate to usedKernel.setKernelCache(new FixIndexKernelCache(cacheSize)). I think maybe it was caused by the maximum value of Integer. Do I have any other cache to run the data set? Thank you!

**Comment by crux82** [comment]
Hi, 

sorry for this very late answer. 
You can you the it.uniroma2.sag.kelp.kernel.cache.FixSizeKernelCache which is implemented into kelp-core.

Hope this help.

Bests

Danilo
