### ISSUE TITLE
Can KeLP kernel functions be used with abstract syntax trees?

### ISSUE THREAD

**Issue by Hareem-E-Sahar** [SAG-KeLP/kelp-full#16]
Hi, 
Unlike natural language text I have source code which I converted to an abstract syntax tree (AST). I want to run tree kernels on these ASTs but I suppose GRCT is not what I need. Even though KeLP is not limited to natural language but at the moment can we use KeLP kernel functions to work with ASTs, of course, with some modifications to the code? What modifications might be needed and do you think it is worthwhile?
Thank you

**Comment by crux82** [comment]
Hi,

Unfortunately, I'm afraid I don't really understand you question. A Grammatical Relation Centered Tree (GRCT) is a specific form of tree. 
If the trees you are referring to (the ASTs) are already generated in the parenthetic form ( http://www.kelp-ml.org/?page_id=39 ) required by KELP, you just need to select a tree kernel function among the ones specified at http://www.kelp-ml.org/?page_id=728 
 
In your case, I would suggest to start by considering a Partial Tree Kernel. You can find an example of a classification task (involving several tree kernels) http://www.kelp-ml.org/?page_id=207 or you can take a look to the demo code https://github.com/SAG-KeLP/kelp-full/blob/development/src/main/java/it/uniroma2/sag/kelp/examples/demo/qc/QuestionClassification.java

Hope it helps

Best regards

Danilo

**Comment by Hareem-E-Sahar** [comment]
Thank you for your response. You said I can use Kernel function if the trees are already generated in the parenthetic form but I think I don't have that right now.
Here's what my abstract syntax tree (AST) representation looks like.
_`{"label": "CompilationUnit", "import_list": [], "statement_list": [{"label": "IfStatement", "condition": {"label": "if conidition", "text": "if(value==1){ \n"}, "then_block": {"label": "BlockStatement", "statements": [{"label": "source line", "text": " System.out.println(\"Hello\") \n"}]}, "else_condition": {"label": "else conidition", "text": "} else { \n"}, "else_block": {"label": "BlockStatement", "statements": [{"label": "source line", "text": " System.out.println(\"World\")\n"}, {"label": "closing brace", "text": "}"}]}}]}`_
Can you please tell me which existing representation shall I use for this or may be provide an example if possible?

**Comment by kamei86i** [comment]
Hi, by parenthetic format we mean the (usual) way of writing parse trees for NLP like the ones specified in http://www.kelp-ml.org/?page_id=39.
So for example, let us assume you have the tree:
![syntax_tree](https://user-images.githubusercontent.com/7414714/82598716-eeded200-9b5f-11ea-8409-716c078e4904.png)

Its parenthetic format is: (ROOT (S (NP (NNP KeLP)) (VP (VBZ is) (ADJP (JJ amazing)))))

**Comment by Hareem-E-Sahar** [comment]
Thank you for response. I got it :)
