### ISSUE TITLE
 Printing subtrees or subset trees of a sentence

### ISSUE THREAD

**Issue by Hareem-E-Sahar** [SAG-KeLP/kelp-full#20]
Is there a function in KeLP to print the subtrees or subset trees of a sentence?

**Comment by SimoneFilice** [comment]
We did not implement that function. The reason is that, for fairly large trees, the number of possible subparts (subtrees, subset trees or partial trees) is extremely large. Basically, an explicit vectorization of the tree kernel space is not feasible. And this is why the kernel trick is efficient.

**Comment by Hareem-E-Sahar** [comment]
Thanks for your answer.
