### ISSUE TITLE
Normalized PTK

### ISSUE THREAD

**Issue by daalft** [SAG-KeLP/kelp-full#3]
For the partial tree kernel, you only have a non-normalized kernel computation. How can I normalize the score?

**Comment by SimoneFilice** [comment]
You can easily normalize a kernel using the it.uniroma2.sag.kelp.kernel.standard.NormalizationKernel. In your case you need to pass the PTK as base kernel to the NormalizationKernel. You can find a description of the NormalizationKernel in section 4.3 of [Kelp_guide](http://sag.art.uniroma2.it/kelp-docs/kelp-guide_2.0.2.pdf). In this case it is convinient using a squared norm kernel cache for the PTK and a kernel cache for the NormalizationKernel details are in section 4.4.2 of [Kelp_guide](http://sag.art.uniroma2.it/kelp-docs/kelp-guide_2.0.2.pdf).
