### ISSUE TITLE
Error when creating maven project 

### ISSUE THREAD

**Issue by dannydrinkswater** [SAG-KeLP/kelp-full#7]
Hi, 
I've encountered some problems when trying to import kelp-full into my maven project. I followed the instruction given in readme.md and edited my pom.xml , however, no jar seems to be download. Could you kindly help me figure out what's the problem. Thanks

**Comment by SimoneFilice** [comment]
Hi,

Please include the repositories specified in [README.md](https://github.com/SAG-KeLP/kelp-input-generator/blob/master/README.md) and add the dependency to the 1.0.1-SNAPSHOT version of kelp-input-generator (kelp-full is already included by kelp-input-generator). Let me know if it works.

Best,
Simone

**Comment by dannydrinkswater** [comment]
Hi Simone,
Thanks for your immediate reply. I can successfully import kelp-input-generator and run the code now. Really appreciate that.

best,
Danny

**Comment by crux82** [comment]
Dear Danny 

thank you very much for your question.
We have also fixed the import procedure of kelp-full: now you can import it also without importing the project kelp-input-generator.

Best

Danilo
