### ISSUE TITLE
Getting tp, tn, fp, and fn for each class in the case of Multi-class classification

### ISSUE THREAD

**Issue by nasrin-taghizadeh** [SAG-KeLP/kelp-full#8]
Hi,
I have a multi-class classification and I need to evaluate the classifier based on micro-averaging measures, e.g. micro-precision, micro-recall and micro-f1. For this purpose, I need to get tp, tn, fp, fn of each class of the problem. Unfortunately, it is not possible to get such information from MulticlassClassificationEvaluator class. Can you please add such capabilities. 

Thanks in advance.

**Comment by SimoneFilice** [comment]
Hi Nasrin,
Currently KeLP does not provide this capability but I'm planning to add it soon. Perhaps, I will add it within this week. I will write here as soon as it will be available.

Regards,
Simone

**Comment by SimoneFilice** [comment]
Hi Nasrin,

I included the capabilities you asked in the development branch of kelp (version 2.2.2-SNAPSHOT). Please check it and let us know if everything is properly working.

Thanks,
Simone
