### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by nasrin-taghizadeh** [SAG-KeLP/kelp-full#9]
Hi,
I have upgraded kelp-full maven dependency to version 2.2.1 recently, after that I got "NegativeArraySizeException" with the last line of the following lines of code:

int cacheSize = trainingSet.getNumberOfExamples();
PartialTreeKernel ptk = new PartialTreeKernel("lct");
ptk.setMu((float) 0.4);
ptk.setLambda((float) 0.4);
ptk.setKernelCache(new FixIndexKernelCache(cacheSize));

I have tested other types of KernelCache and I got the same error. While with previous version I did not get such errors. If I should set somethings or add some codes, can you please direct me.

Regards

**Comment by crux82** [comment]
Dear nasrin-taghizadeh

unfortunately the FixIndexKernelCache is deprecated.
Did you also used the SimpleDynamicKernelCache?

If the error persists, can you send the entire stack trace?

Best regards

Danilo

**Comment by SimoneFilice** [comment]
Hi Nasrin,

If you know in advance the size of your dataset, please use FixSizeKernelCache, otherwise use SimpleDynamicKernelCache as Danilo suggested. A tutorial about how to use the caching mechanism on KeLP is in my TODO list.

Best,
Simone
